version: "3.6"

services:

  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=poll
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data
      
  geolocation:
    build:
      context: geolocation
    ports:
      - 8443:8443
      
  api:
    build:
      context: api
    ports:
      - 8181:8181
#  
#  audit:
#    build:
#      context: audit
#    ports:
#      - 8081:8081
    
volumes:
  rabbitmq_data:
  postgres_data: