version: "3.6"

services:
  api:
    build: .
    image: garage-api
    ports:
      - 8080:8080
  
  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_DB=poll
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432